name: PR Title
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the escaped PR title
        run: |
          title="${{ fromJSON( toJSON( github.event.pull_request.title ) ) }}"
          echo -E $title | sed "s/'/\'/" > file.md
      - name: Upload file.md        
        uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.md

